# Generated by Django 2.0.2 on 2018-06-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20180624_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userage',
            name='user_name',
        ),
    ]
