# Generated by Django 2.0.2 on 2018-06-25 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_remove_userage_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userage',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=264),
        ),
    ]
