# Generated by Django 2.0.2 on 2018-06-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20180625_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
